# Generated by Django 3.1.7 on 2021-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('enrollment', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('oxygen', models.FloatField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
