# Generated by Django 3.1.7 on 2021-03-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_auto_20210322_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='flag',
        ),
    ]
